name: Run LeetCode Daily Tracker

on:
  # Trigger manually using GitHub UI and run on a schedule
  workflow_dispatch:
  
  schedule:
    # Run at 7:00 AM, 12:00 PM, 3:00 PM, and 8:00 PM UTC
    - cron: '0 7,12,15,20 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the LeetCode Daily Tracker script
        run: node main.js

      - name: Show current time for testing
        run: date
