name: Run LeetCode Daily Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,15,20 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the LeetCode Daily Tracker script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          REC_MAIL: ${{ secrets.REC_MAIL }}
        run: node main.js
