name: Run LeetCode Daily Tracker

on:
  workflow_dispatch:
  schedule:
      # 12 AM IST (6:30 PM UTC the previous day)
      - cron: '30 18 * * *'
      # 7 AM IST (1:30 AM UTC)
      - cron: '30 0 * * *'
      # 3 PM IST (9:30 AM UTC)
      - cron: '30 9 * * *'
      # 8 PM IST (2:30 PM UTC)
      - cron: '0 16 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the LeetCode Daily Tracker script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          REC_MAIL: ${{ secrets.REC_MAIL }}
        run: node main.js
